name: Gitleaks Secrets Scan for jenkins-backup master branch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check-for-secrets:
    uses: minutuscomputing/jenkins-backup/.github/workflows/jenkins-backup_main.yml@main
    secrets:
      token: ${{ secrets.MY_GITHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}